# Instructions pour la consttruction du cotainer pour la bd mysql

# Base image
FROM mysql:latest

# Environment Variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=inchassurdb
ENV MYSQL_USER=kevin
ENV MYSQL_PASSWORD=kevin.

# expose the port
EXPOSE 3306